# Generated by Django 3.2.3 on 2021-05-28 22:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('uniqueCode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Code Unique Generate')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name TypeEntity')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('uniqueCode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Code Unique Generate')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name Entity')),
                ('typeEntity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entitys.typeentity')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Model',
                'abstract': False,
            },
        ),
    ]
